package nl.ladyminks.thirtyoneseconds.logic.factories;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Name Generator generates a team Name by randomly picking one String out of all 3 Lists.
 *
 * @author Minka Firth
 */
public class NameFactory {

    private final Random random;

    public static NameFactory makeHardCodedGenerator() {
        final List<String> adjectives = new ArrayList<String>();
        adjectives.add("Golden");
        adjectives.add("Stinky");
        adjectives.add("Pretty");
        adjectives.add("Delicious");
        adjectives.add("Amazing");
        adjectives.add("Unceasing");
        adjectives.add("Adroit");
        adjectives.add("Aloof");
        adjectives.add("Antic");
        adjectives.add("Baleful");
        adjectives.add("Capricious");
        adjectives.add("Comely");
        adjectives.add("Dapper");
        adjectives.add("Debonair");
        adjectives.add("Elated");
        adjectives.add("Jocular");
        adjectives.add("Luminous");
        adjectives.add("Munificent");
        adjectives.add("Penitent");
        adjectives.add("Placid");
        adjectives.add("Sordid");
        adjectives.add("Tenacious");
        adjectives.add("Verdant");
        adjectives.add("Zealous");
        adjectives.add("Witty");

        final List<String> nouns = new ArrayList<String>();
        nouns.add("Wine");
        nouns.add("Flower");
        nouns.add("Cake");
        nouns.add("Cat");
        nouns.add("Sequel");
        nouns.add("Java");
        nouns.add("Grill");
        nouns.add("Bacon");
        nouns.add("Blend");
        nouns.add("Wasp");
        nouns.add("Bidet");
        nouns.add("Bear");
        nouns.add("App");
        nouns.add("Fringe");
        nouns.add("Mushroom");
        nouns.add("Rugby");
        nouns.add("Executive");
        nouns.add("Goggle");
        nouns.add("Flavour");
        nouns.add("Status");

        final List<String> verbers = new ArrayList<String>();
        verbers.add("eaters");
        verbers.add("lovers");
        verbers.add("players");
        verbers.add("makers");
        verbers.add("destroyers");
        verbers.add("lurkers");
        verbers.add("stealers");
        verbers.add("minters");
        verbers.add("swipers");
        verbers.add("swooners");
        verbers.add("musers");
        verbers.add("cravers");
        verbers.add("bakers");
        verbers.add("crashers");

        return new NameFactory(new Random(), adjectives, nouns, verbers);
    }

    private final List<String> adjectives;
    private final List<String> nouns;
    private final List<String> verbers;

    public NameFactory(Random random, List<String> adjectives, List<String> nouns, List<String> verbers) {
        this.random = random;
        this.adjectives = adjectives;
        this.nouns = nouns;
        this.verbers = verbers;
    }

    public String generateName() {

        String adjective = adjectives.get(random.nextInt(adjectives.size()));
        String noun = nouns.get(random.nextInt(nouns.size()));
        String verber = verbers.get(random.nextInt(verbers.size()));

        String autoGeneratedName = adjective + " " + noun + "-" + verber;

        return autoGeneratedName;
    }
}
